name = "email-collector"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "EMAIL_SIGNUPS"
id = "e4c1d15f6b6e4d8da826b00d16c66bab"

[[kv_namespaces]]
binding = "ONBOARDING_RESPONSES"
id = "5d841b8ebe74407bb419490d095d979f"

[[kv_namespaces]]
binding = "WORKSHOP_FEEDBACK"
id = "5dd88914ff5e46fdb24250e30bd21e13"
